"""Add user_strategies table

Revision ID: c60473224f7d
Revises: ba54375702ac
Create Date: 2026-02-13 02:08:55.461698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60473224f7d'
down_revision: Union[str, None] = 'ba54375702ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_strategies_id'), 'user_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_user_strategies_user_id'), 'user_strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_strategies_user_id'), table_name='user_strategies')
    op.drop_index(op.f('ix_user_strategies_id'), table_name='user_strategies')
    op.drop_table('user_strategies')
    # ### end Alembic commands ###
